"""
Database Layer
--------------
Uses SQLite (zero setup — just a file on disk).
Later you can swap to PostgreSQL by changing DATABASE_URL.

Tables:
  - devices       : every agent-device registered
  - system_reports: CPU/RAM/disk snapshots
  - port_scans    : port scan results
  - file_events   : file changes, deletions, recoveries
  - alerts        : security alerts generated
  - snapshots     : file vault snapshot records
"""

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker, Session
from sqlalchemy import (
    Column, String, Integer, Float, Boolean,
    DateTime, Text, JSON, ForeignKey
)
from datetime import datetime

# ── Database URL ──────────────────────────────────────────────────────────────
# SQLite file — stored right in the server folder, zero config needed
# Using sync engine to avoid greenlet/Python 3.14 compatibility issues
DATABASE_URL = "sqlite:///./zyvaron.db"

engine = create_engine(DATABASE_URL, echo=False, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


# ── Base Model ────────────────────────────────────────────────────────────────

class Base(DeclarativeBase):
    pass


# ── Tables ────────────────────────────────────────────────────────────────────

class Device(Base):
    """One row per agent device registered with the server."""
    __tablename__ = "devices"

    id            = Column(String, primary_key=True)   # agent_id from agent
    hostname      = Column(String, index=True)
    platform      = Column(String)                     # Windows / Linux / Darwin
    architecture  = Column(String)
    ip_address    = Column(String)
    first_seen    = Column(DateTime, default=datetime.utcnow)
    last_seen     = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_active     = Column(Boolean, default=True)
    agent_version = Column(String)
    risk_score    = Column(Integer, default=0)         # overall risk 0-100
    indexed_files = Column(Integer, default=0)         # total files being monitored


class SystemReport(Base):
    """CPU / RAM / disk snapshot from an agent."""
    __tablename__ = "system_reports"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    device_id       = Column(String, ForeignKey("devices.id"), index=True)
    reported_at     = Column(DateTime, default=datetime.utcnow)

    # CPU
    cpu_cores       = Column(Integer)
    cpu_usage       = Column(Float)

    # Memory
    ram_total_gb    = Column(Float)
    ram_used_gb     = Column(Float)
    ram_percent     = Column(Float)

    # Platform
    os_platform     = Column(String)
    os_release      = Column(String)
    hostname        = Column(String)
    uptime_seconds  = Column(Integer)

    # Full raw data stored as JSON
    raw_data        = Column(JSON)


class PortScanReport(Base):
    """Results of a port scan from an agent."""
    __tablename__ = "port_scan_reports"

    id                  = Column(Integer, primary_key=True, autoincrement=True)
    device_id           = Column(String, ForeignKey("devices.id"), index=True)
    scanned_at          = Column(DateTime, default=datetime.utcnow)

    target              = Column(String)
    ports_scanned       = Column(Integer)
    total_open          = Column(Integer)
    risk_score          = Column(Integer)
    critical_exposures  = Column(Integer)
    status              = Column(String)           # CLEAN / WARNING / CRITICAL

    open_ports          = Column(JSON)             # List of port details
    scan_duration       = Column(Float)


class FileEvent(Base):
    """A file change, deletion, or recovery detected by the agent."""
    __tablename__ = "file_events"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    device_id    = Column(String, ForeignKey("devices.id"), index=True)
    detected_at  = Column(DateTime, default=datetime.utcnow)

    event_type   = Column(String)    # modified / deleted / new / recovered
    file_path    = Column(String)
    severity     = Column(String)    # LOW / MEDIUM / HIGH / CRITICAL
    original_hash= Column(String, nullable=True)
    current_hash = Column(String, nullable=True)
    resolved     = Column(Boolean, default=False)


class Alert(Base):
    """Security alerts generated by the server."""
    __tablename__ = "alerts"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    device_id    = Column(String, ForeignKey("devices.id"), index=True)
    created_at   = Column(DateTime, default=datetime.utcnow)

    alert_type   = Column(String)    # port_risk / file_deleted / high_cpu / etc
    severity     = Column(String)    # LOW / MEDIUM / HIGH / CRITICAL
    title        = Column(String)
    description  = Column(Text)
    data         = Column(JSON)      # Extra context
    resolved     = Column(Boolean, default=False)
    resolved_at  = Column(DateTime, nullable=True)


class SnapshotRecord(Base):
    """File vault snapshot records."""
    __tablename__ = "snapshots"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    device_id    = Column(String, ForeignKey("devices.id"), index=True)
    snapshot_id  = Column(String, unique=True)
    created_at   = Column(DateTime, default=datetime.utcnow)
    total_files  = Column(Integer)
    label        = Column(String, nullable=True)


# ── Init ──────────────────────────────────────────────────────────────────────

def init_db():
    """Create all tables if they don't exist."""
    Base.metadata.create_all(bind=engine)


def get_db():
    """Dependency injection — gives each request its own DB session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ── CVE Scan Results ──────────────────────────────────────────────────────────
class CVEScan(Base):
    __tablename__ = "cve_scans"
    id             = Column(Integer, primary_key=True, autoincrement=True)
    device_id      = Column(String, ForeignKey("devices.id"), index=True)
    scanned_at     = Column(DateTime, default=datetime.utcnow)
    apps_scanned   = Column(Integer, default=0)
    apps_total     = Column(Integer, default=0)
    total_cves     = Column(Integer, default=0)
    critical_count = Column(Integer, default=0)
    high_count     = Column(Integer, default=0)
    medium_count   = Column(Integer, default=0)
    cves           = Column(JSON, default=list)        # full CVE list
    software_list  = Column(JSON, default=list)        # installed software


class CVEEntry(Base):
    __tablename__ = "cve_entries"
    id          = Column(Integer, primary_key=True, autoincrement=True)
    device_id   = Column(String, ForeignKey("devices.id"), index=True)
    scan_id     = Column(Integer, ForeignKey("cve_scans.id"), index=True)
    cve_id      = Column(String, index=True)           # e.g. CVE-2024-1234
    software    = Column(String)
    version     = Column(String)
    score       = Column(Float)
    severity    = Column(String)                       # CRITICAL/HIGH/MEDIUM
    description = Column(String)
    published   = Column(String)
    url         = Column(String)
    resolved    = Column(Boolean, default=False)
    detected_at = Column(DateTime, default=datetime.utcnow)
